version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: .
    container_name: backend_container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb
volumes:
  postgres_data:
