const express = require('express')
const app = express()
const user_routes = require('./src/user/user.routes')
const profil_routes = require('./src/profil/profil.routes')
const experience_routes = require('./src/experience/experience.routes')
const userskill_routes = require('./src/userskill/userskill.routes')
const skill_routes = require('./src/skill/skill.routes')
const notification_routes = require('./src/notification/notification.routes')
const experienceskill_routes = require('./src/experienceskill/experienceskill.routes')
const project_routes = require('./src/project/project.routes')
const projectskill_routes = require('./src/projectskill/projectskill.routes')
const contributor_routes = require('./src/contributor/contributor.routes')
const messages_routes = require('./src/messages/messages.routes')
const application_routes = require('./src/application/application.routes')
const favorites_routes = require('./src/favorites/favorites.routes')
const topicproject_routes = require('./src/topicproject/topicproject.routes')
const topic_routes = require('./src/topic/topic.routes')

const port = process.env.PORT || 3000
const project_name = process.env.PROJECT_NAME || 'new_project'

app.use(express.json())

app.get('/', (req, res) => res.send('Hammer did strike again !'))

app.use('/user', user_routes)
app.use('/profil', profil_routes)
app.use('/experience', experience_routes)
app.use('/userskill', userskill_routes)
app.use('/skill', skill_routes)
app.use('/notification', notification_routes)
app.use('/experienceskill', experienceskill_routes)
app.use('/project', project_routes)
app.use('/projectskill', projectskill_routes)
app.use('/contributor', contributor_routes)
app.use('/messages', messages_routes)
app.use('/application', application_routes)
app.use('/favorites', favorites_routes)
app.use('/topicproject', topicproject_routes)
app.use('/topic', topic_routes)

app.listen(port, () => console.log(`Server running on port 3000`))
