name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install SSH Client
      run: sudo apt-get install -y sshpass

    - name: Execute Deployment Script on VPS
      env:
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
            run: |
        sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOST << 'EOF'
          cd ~/project/COFOUND/backend || exit 1
          
          echo "Checking if port 3000 is in use..."
          PID=\$(sudo lsof -t -i:3000) || true
          if [ -n "\$PID" ]; then
            echo "Port 3000 is in use. Killing process \$PID..."
            sudo kill -9 \$PID
            echo "Freed port 3000."
          else
            echo "Port 3000 is free."
          fi

          echo "Pulling latest code..."
          git pull origin main

          echo "Installing dependencies..."
          npm install

          echo "Building the application..."
          npm run build

          echo "Restarting the application if running..."
          if command -v pm2 >/dev/null 2>&1; then
            # Gracefully reload the application with PM2
            pm2 reload "cofound-api" || pm2 start npm --name "cofound-api" -- start
            pm2 save
          else
            echo "PM2 is not installed. Please manage the application manually."
          fi

          echo "Checking application status..."
          STATUS=\$(pm2 status "cofound-api" | grep "errored" || true)
          if [ -n "\$STATUS" ]; then
            echo "Application is in an error state. Exiting with failure."
            exit 1
          fi

          echo "Deployment complete!"
        EOF
